### ISSUE TITLE
Per user status page

### ISSUE THREAD

**Issue by riconnon** [ShaneMcC/AoCBench#18]
Would be nice to see all the information about a single user on one page, including:
- Have you provided inputs and answers for all days
- Have you passed each day with everyone's inputs
- Last execution time/revision per day

Stretch goal:
- Are any of your days queued for execution

**Comment by ShaneMcC** [comment]
Started work on this on the `/health.php` page.

**Comment by ShaneMcC** [comment]
This is basically complete now I think.

I can't do "Are any of your days queued for execution" directly, as it doesn't know (The scheduler just schedules the entire event to rerun and then that script decides what needs to happen)
