### ISSUE TITLE
Per-day leaderboards

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/AoCBench#20]
It would be nice to be able to drill down and see a day's leaderboard individually.

It's a bit hard to scan the large table to figure out who's 4th, 5th, etc, and what the difference is.

An individual day page can order people by their time, and show the differences like they do sports, e.g.:

<table>
<tr><th>Rank<th>Person<th>Language<th>Time<th>Difference
<tr>
 <td>1.
 <td>Bob
 <td>C
 <td>300us
 <td>-
<tr>
 <td>2.
 <td>Alice
 <td>Rust
 <td>800us
 <td>+500us
<tr>
 <td>3.
 <td>Carol
 <td>PHP
 <td>37,000us
 <td>+36,700us

</table>

**Comment by csmith** [comment]
You could also have box plots of each person's time, showing the min/max/mean nicely in one view 🤩

**Comment by ShaneMcC** [comment]
This is now mostly handled by `/ranking.php`

I've not done the boxplots yet.

**Comment by ShaneMcC** [comment]
Closing as completed for now, can revisit box plots later.

PRs welcome.
