### ISSUE TITLE
User-visible information on runs in progress

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/AoCBench#22]
It's a bit frustrating to push something and then... nothing happens.

It'd be nice to see logs as they happen, or at least have some kind of indicator that a run is in progress (and when it started?).

**Comment by ShaneMcC** [comment]
This has now been done as best as I can with the current multi-box setup.

Information may be a couple of minutes delayed (various cronjobs only run every minute) but banners will now appear if benchmark runs are scheduled/running.
